M48
; DRILL file {KiCad 7.0.10} date Wednesday, March 20, 2024 at 06:29:43 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-20T18:29:43+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0472
%
G90
G05
T1
X4.13Y-2.5831
X4.13Y-2.78
X4.13Y-2.9769
T2
X3.8307Y-2.5827
X3.8307Y-2.7795
X3.8307Y-2.9764
M30
